#AddressSpace
INTERNET = 1
INTRANET = 2

#Industry
JDCOM = 1
JDCLOUD = 2

#AssignStatus
IDLE = 0
RESERVED = 1
ASSIGNED = 2
QUARANTINE = 3

#AddressFamily
IPV4 = 4
IPV6 = 6

#CastType
UNICAST = 1
ANYCAST = 2
MULTICAST = 3

#NetworkType
DYNAMIC = BGP = 1
PROXYCAST = 2
CHINATELECOM = 3
CHINAUNICOM = 4
CHINAMOBILE = 5
COMMON = 6
DUALDYNAMIC = BGP = 7
EDUCATIONNETWORK = 8
NULL = 0

#UsageType
SERVERSERVICEADDRESS = 1
SERVERMANAGENTADDRESS = 2
VITRUALSERVERADDRESS = 3
NETWORKDVICEINBANDMANAGEMENTADDRESS = 4
NETWORKDVICEINBANDMANAGEMENTADDRESS = 5
NETWORKDEVICEINTERCONNECTIONADDRESS = 6
SERVERINTERCONNECTIONADDRESS = 7
